### ISSUE TITLE
Post UAT UI iteration 1 - Issue with building UI for first time after cloning from repo

### ISSUE THREAD

**Issue by Cherrett** [SimplyVC/panic#120]
When cloning from gitlab and building via docker for the first time, the build fails because stencil.js fails to build the UI service. To solve this issue you have to do:

```bash
cd ui
npm install
npm run build
npm run build
```

We need to investigate why this issue is happening, but it seems that the issue stems from the fact that the `components.d.ts` file is not included in git. One possible solution is thus to include this file.

**Comment by dillu24** [comment]
- Issue with building via docker first time after cloning from repo. To solve this issue you need to do:
    ```
    cd ui
    npm install
    npm run build
    npm run build
    ```
    We need to investigate why this issue is happening, but it seems that the issue stems from the fact that the components.d.ts file is not included in git.

- API not accessible by the UI:
[IP-1647270241492.log](https://github.com/SimplyVC/panic/files/8246261/172.16.152.17-1647270241492.log)

- Issue in Binance Smart Chain Monitoring:

```
15/03/2022 08:42:46 AM - ChainlinkContractsMonitor - DEBUG - Retrieved prometheus data from endpoint: https://172.16.152.175:2002/metrics
15/03/2022 08:42:46 AM - ChainlinkContractsMonitor - ERROR - Could not transact with/call contract function, is contract deployed correctly and chain synced?
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/web3/contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/panic/alerter/src/monitors/monitor.py", line 92, in start
    self._monitor()
  File "/opt/panic/alerter/src/monitors/contracts/chainlink.py", line 684, in _monitor
    node_contracts = self._filter_contracts_by_node(
  File "/opt/panic/alerter/src/monitors/contracts/chainlink.py", line 253, in _filter_contracts_by_node
    transmitters = aggregator_contract.functions.transmitters() \
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/web3/contract.py", line 1530, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```
