### ISSUE TITLE
Substrate API Updating for Schema Error

### ISSUE THREAD

**Issue by itsciccio** [SimplyVC/panic#365]
### Description

The data retrieved by the Substrate API does not match the schema that PANIC accounts for, meaning that our schema is wrong or we are using an outdated API version.

Error log:

```
Traceback (most recent call last):
  File "/opt/panic/alerter/src/data_transformers/networks/substrate.py", line 648, in _process_raw_data
    self._update_state(transformed_data)
  File "/opt/panic/alerter/src/data_transformers/networks/substrate.py", line 229, in _update_state
    update_fn(transformed_data[data_type])
  File "/opt/panic/alerter/src/data_transformers/networks/substrate.py", line 202, in _update_websocket_state
    network.set_active_proposals(metrics['active_proposals'])
  File "/opt/panic/alerter/src/monitorables/networks/substrate.py", line 74, in set_active_proposals
    if self._are_new_active_proposals_valid(new_active_proposals):
  File "/opt/panic/alerter/src/monitorables/networks/substrate.py", line 70, in _are_new_active_proposals_valid
    schema.validate(new_active_proposals)
  File "/root/.local/share/virtualenvs/alerter-GNVLrDHs/lib/python3.9/site-packages/schema.py", line 445, in validate
    raise SchemaError([None] + x.autos, [e.format(data) if e else None] + x.errors)
schema.SchemaError: Or([{'index': Or(<class 'int'>, None), 'balance': Or(<class 'int'>, None), 'image': {'at': Or(<class 'int'>, None), 'balance': Or(<class 'int'>, None)}, 'imageHash': Or(<class 'str'>, None), 'proposer': Or(<class 'str'>, None), 'seconds': Or([<class 'str'>], []), 'seconded': Or({<class 'str'>: <class 'bool'>}, {})}], [], None) did not validate [{'index': 71, 'balance': 3400000000, 'image': {'at': 13227437, 'balance': 239997600}, 'imageHash': '0x22a2dab6cacac5fbd994705f5c22d06e878ae4ccd64731f5f9627c9482500cf9', 'proposer': 'EvoLanodoqDsgHb98Ymbu41uXXKfCPDKxeM6dXHyJ2JoVus', 'seconds': ['EvoLanodoqDsgHb98Ymbu41uXXKfCPDKxeM6dXHyJ2JoVus' ......
````

### Requirements

- [x] Update Substrate API
- [x] Obtain the data 
- [x] Check if data contains mismatch
- [x] Fix schema as necessary

### Acceptance criteria

**Scenario**: Data obtained from Substrate API passes through Data Transformer component
**Given**: PANIC is running correctly with no error logs
**When**: Data retrieved from Substrate API
**Then**: No error is present in the logs

**Comment by itsciccio** [comment]
The only requirement was an API upgrade 9.5.1
